### ISSUE TITLE
ER2 - NEW PUZZLE - Handheld torch

### ISSUE THREAD

**Issue by jaspreetdhanjan** [nfynt/EscapeRoom_MR#2]
In the story outline, there is a requirement for the player to use a torch in one of three situations:
1. As a light source
2. As a UV source
3. As a lightsaber (for battle)

This should be implemented in the game.

**Comment by jaspreetdhanjan** [comment]
Alongside this ticket, we should include the wall with the hidden text.

**Comment by nfynt** [comment]
Done.

The hidden message is pending though
