### ISSUE TITLE
ER4 - NEW PUZZLE - Jigsaw

### ISSUE THREAD

**Issue by jaspreetdhanjan** [nfynt/EscapeRoom_MR#4]
We must provide a 3x3 Jigsaw puzzle. Only two pieces are currently in there. The remaining seven pieces must be found to complete the puzzle.

**Comment by jaspreetdhanjan** [comment]
To consider this ticket as complete, the following must be achieved:

Each piece should be available at:
1. One is hidden on the top of the bookshelf
2. One is hidden in one of the books -> hid between two books
3. One is in a Lockbox (stage 2c) -> placed under the table
4. One is hidden in a glass box（physical but does not have to be a glass box, just use table, but add glass breaking sound afterwards） (player should use the torch to break it, and when it is being broken, add some acoustic effect)
5. One is hidden behind the computer
6. One is not hidden, just on the floor (probably behind some boxes) to lead the player to the jigsaw puzzle
7. One is hidden in a drawer (can be physical) (There are two things in the drawer, one is the jigsaw piece, the other is a mirror (can be physical))

**Comment by nfynt** [comment]
Just the mechanics of jigsaw puzzle has been implemented... 
All the points will be addressed with the level design
